/**
 * Lightweight copy tables for the mobile agent management views.
 *
 * The agents H5 package does not depend on i18next; these views ship their own
 * zh/en copy tables (same shape as `messageInputI18n`) so host apps such as
 * sdkwork-im-h5 can embed them without wiring a shared i18n runtime.
 */

export type AgentH5Locale = 'zh' | 'en';

export const MOBILE_AGENT_COPY: Record<AgentH5Locale, Record<string, string>> = {
  zh: {
    'agents.mobile.back': '返回',
    'agents.mobile.title': '我的智能体',
    'agents.mobile.create': '创建',
    'agents.mobile.status.draft': '草稿',
    'agents.mobile.status.active': '已发布',
    'agents.mobile.status.disabled': '已停用',
    'agents.mobile.status.archived': '已归档',
    'agents.mobile.status.deleted': '已删除',
    'agents.mobile.status.published': '已发布',
    'agents.mobile.group.active': '我的智能体',
    'agents.mobile.group.deleted': '已删除',
    'agents.mobile.loading': '加载中...',
    'agents.mobile.loadMore': '加载更多',
    'agents.mobile.loadingMore': '加载中...',
    'agents.mobile.noMore': '没有更多了',
    'agents.mobile.error.title': '加载失败',
    'agents.mobile.error.desc': '网络异常或服务暂不可用，请稍后重试',
    'agents.mobile.error.retry': '重试',
    'agents.mobile.empty.title': '打造专属 AI 助手',
    'agents.mobile.empty.desc': '定制懂你的 AI 智能体，提升工作与生活效率',
    'agents.mobile.empty.create': '立即创建',
    'agents.mobile.empty.deleted': '暂无已删除的智能体',
    'agents.mobile.menu.edit': '修改配置',
    'agents.mobile.menu.delete': '删除智能体',
    'agents.mobile.menu.restore': '恢复',
    'agents.mobile.confirm.delete.title': '删除智能体',
    'agents.mobile.confirm.delete.desc': '删除后可在「已删除」中恢复，确定删除「{{name}}」吗？',
    'agents.mobile.confirm.cancel': '取消',
    'agents.mobile.confirm.ok': '确定',
    'agents.mobile.toast.deleted': '已删除',
    'agents.mobile.toast.restored': '已恢复',
    'agents.mobile.toast.deleteFailed': '删除失败，请重试',
    'agents.mobile.toast.restoreFailed': '恢复失败，请重试',
    'agents.mobile.toast.loadFailed': '加载智能体失败',
    'agents.mobile.pullToRefresh': '下拉刷新',
    'agents.mobile.releaseToRefresh': '松开刷新',
    'agents.mobile.refreshing': '刷新中...',
    'agents.mobile.form.title.create': '创建智能体',
    'agents.mobile.form.title.edit': '修改配置',
    'agents.mobile.form.save': '保存',
    'agents.mobile.form.saving': '保存中...',
    'agents.mobile.form.publish': '发布',
    'agents.mobile.form.publishing': '发布中...',
    'agents.mobile.form.avatar': '头像',
    'agents.mobile.form.avatar.change': '更换头像',
    'agents.mobile.form.avatar.uploaded': '头像已选择',
    'agents.mobile.form.name': '名称',
    'agents.mobile.form.name.placeholder': '给智能体起个名字',
    'agents.mobile.form.name.required': '请输入智能体名称',
    'agents.mobile.form.description': '简介',
    'agents.mobile.form.description.placeholder': '一句话介绍智能体的用途',
    'agents.mobile.form.persona': '人设提示词',
    'agents.mobile.form.persona.placeholder': '定义智能体的角色、性格与能力边界',
    'agents.mobile.form.model': '模型',
    'agents.mobile.form.model.placeholder': '选择模型',
    'agents.mobile.form.model.custom': '自定义模型',
    'agents.mobile.form.model.loadFailed': '模型列表加载失败',
    'agents.mobile.form.temperature': '温度',
    'agents.mobile.form.temperature.desc': '越高回复越随机，越低越稳定',
    'agents.mobile.form.memory': '长记忆',
    'agents.mobile.form.memory.desc': '记住对话上下文，提供连续服务',
    'agents.mobile.form.welcome': '开场白',
    'agents.mobile.form.welcome.placeholder': '智能体主动发出的问候语',
    'agents.mobile.form.suggestedPrompts': '快捷提问',
    'agents.mobile.form.suggestedPrompts.add': '添加提问',
    'agents.mobile.form.suggestedPrompts.placeholder': '如：你能帮我做什么？',
    'agents.mobile.form.toast.created': '智能体已创建',
    'agents.mobile.form.toast.updated': '已保存修改',
    'agents.mobile.form.toast.published': '已发布',
    'agents.mobile.form.toast.createFailed': '创建失败，请重试',
    'agents.mobile.form.toast.updateFailed': '保存失败，请重试',
    'agents.mobile.form.toast.publishFailed': '发布失败，请重试',
    'agents.mobile.form.toast.loadFailed': '智能体不存在或无权访问',
    'agents.mobile.form.toast.promptTooLong': '提示词不能超过 32768 字符',
    'agents.mobile.characters.title': '我的角色',
    'agents.mobile.characters.create': '新建',
    'agents.mobile.characters.empty': '还没有角色，点击右上角创建一个吧',
    'agents.mobile.characters.menu.edit': '编辑角色',
    'agents.mobile.characters.menu.delete': '删除角色',
    'agents.mobile.characters.confirm.delete.title': '删除角色',
    'agents.mobile.characters.confirm.delete.desc': '确定删除「{{name}}」吗？',
    'agents.mobile.characters.confirm.cancel': '取消',
    'agents.mobile.characters.confirm.ok': '确定',
    'agents.mobile.characters.toast.deleted': '已删除',
    'agents.mobile.characters.form.title.create': '新建角色',
    'agents.mobile.characters.form.title.edit': '编辑角色',
    'agents.mobile.characters.form.save': '保存角色',
    'agents.mobile.characters.form.name': '名字',
    'agents.mobile.characters.form.name.placeholder': '例如：旅行规划师',
    'agents.mobile.characters.form.name.required': '请输入名字',
    'agents.mobile.characters.form.voice': '关联声音',
    'agents.mobile.characters.form.voice.placeholder': '请选择声音',
    'agents.mobile.characters.form.desc.label': '角色设定 / 描述信息',
    'agents.mobile.characters.form.desc.placeholder': '详细描述这个角色的性格、功能或设定背景...',
    'agents.mobile.characters.form.toast.created': '角色创建成功',
    'agents.mobile.characters.form.toast.updated': '角色已更新',
    'agents.mobile.characters.detail.title': '角色详情',
    'agents.mobile.characters.detail.visibility.private': '私密角色',
    'agents.mobile.characters.detail.systemPrompt': '系统设定',
    'agents.mobile.characters.detail.systemPrompt.empty': '无设定内容',
    'agents.mobile.characters.detail.voice': '使用的声音',
    'agents.mobile.characters.detail.voice.default': '默认声音',
    'agents.mobile.characters.detail.chat': '与TA聊天',
    'agents.mobile.characters.detail.edit': '编辑角色',
    'agents.mobile.market.search': '搜索',
    'agents.mobile.market.search.placeholder': '搜索智能体',
    'agents.mobile.market.search.cancel': '取消',
    'agents.mobile.market.search.clear': '清空',
    'agents.mobile.market.search.empty': '没有找到相关智能体',
    'agents.mobile.market.create': '创建智能体',
    'agents.mobile.market.category.all': '精选',
    'agents.mobile.market.category.study': '学习',
    'agents.mobile.market.category.work': '工作',
    'agents.mobile.market.category.create': '创作',
    'agents.mobile.market.category.life': '生活',
    'agents.mobile.market.category.fun': '娱乐',
    'agents.mobile.market.category.emotion': '情感',
    'agents.mobile.market.category.game': '游戏',
    'agents.mobile.market.category.coding': '编程',
    'agents.mobile.market.category.drawing': '绘画',
    'agents.mobile.market.category.photo': '拍照问',
    'agents.mobile.market.category.device': '硬件',
    'agents.mobile.market.hot.title': '热门搜索',
    'agents.mobile.market.hot.coding': '代码助手',
    'agents.mobile.market.hot.writing': '小红书文案',
    'agents.mobile.market.hot.english': '英语口语教练',
    'agents.mobile.market.hot.office': '简历优化',
    'agents.mobile.market.hot.life': '旅行规划',
    'agents.mobile.market.toast.loadFailed': '加载智能体失败',
    'agents.mobile.market.error.title': '加载失败',
    'agents.mobile.market.error.desc': '网络异常或服务暂不可用，请稍后重试',
    'agents.mobile.market.error.retry': '重试',
    'agents.mobile.market.empty.title': '暂无智能体',
    'agents.mobile.market.empty.desc': '发现智能体生态，先创建一个试试吧',
    'agents.mobile.market.empty.create': '立即创建',
  },
  en: {
    'agents.mobile.back': 'Back',
    'agents.mobile.title': 'My Agents',
    'agents.mobile.create': 'Create',
    'agents.mobile.status.draft': 'Draft',
    'agents.mobile.status.active': 'Published',
    'agents.mobile.status.disabled': 'Disabled',
    'agents.mobile.status.archived': 'Archived',
    'agents.mobile.status.deleted': 'Deleted',
    'agents.mobile.status.published': 'Published',
    'agents.mobile.group.active': 'My Agents',
    'agents.mobile.group.deleted': 'Recently Deleted',
    'agents.mobile.loading': 'Loading...',
    'agents.mobile.loadMore': 'Load more',
    'agents.mobile.loadingMore': 'Loading...',
    'agents.mobile.noMore': 'No more',
    'agents.mobile.error.title': 'Failed to load',
    'agents.mobile.error.desc': 'Network error or service unavailable, please retry later',
    'agents.mobile.error.retry': 'Retry',
    'agents.mobile.empty.title': 'Build Your Own AI Assistant',
    'agents.mobile.empty.desc': 'Create an agent tailored to you to boost work and life efficiency',
    'agents.mobile.empty.create': 'Create now',
    'agents.mobile.empty.deleted': 'No deleted agents yet',
    'agents.mobile.menu.edit': 'Edit config',
    'agents.mobile.menu.delete': 'Delete agent',
    'agents.mobile.menu.restore': 'Restore',
    'agents.mobile.confirm.delete.title': 'Delete agent',
    'agents.mobile.confirm.delete.desc': 'You can restore it from "Recently Deleted". Delete "{{name}}"?',
    'agents.mobile.confirm.cancel': 'Cancel',
    'agents.mobile.confirm.ok': 'OK',
    'agents.mobile.toast.deleted': 'Deleted',
    'agents.mobile.toast.restored': 'Restored',
    'agents.mobile.toast.deleteFailed': 'Failed to delete, please retry',
    'agents.mobile.toast.restoreFailed': 'Failed to restore, please retry',
    'agents.mobile.toast.loadFailed': 'Failed to load agents',
    'agents.mobile.pullToRefresh': 'Pull to refresh',
    'agents.mobile.releaseToRefresh': 'Release to refresh',
    'agents.mobile.refreshing': 'Refreshing...',
    'agents.mobile.form.title.create': 'Create Agent',
    'agents.mobile.form.title.edit': 'Edit Config',
    'agents.mobile.form.save': 'Save',
    'agents.mobile.form.saving': 'Saving...',
    'agents.mobile.form.publish': 'Publish',
    'agents.mobile.form.publishing': 'Publishing...',
    'agents.mobile.form.avatar': 'Avatar',
    'agents.mobile.form.avatar.change': 'Change avatar',
    'agents.mobile.form.avatar.uploaded': 'Avatar selected',
    'agents.mobile.form.name': 'Name',
    'agents.mobile.form.name.placeholder': 'Give your agent a name',
    'agents.mobile.form.name.required': 'Please enter an agent name',
    'agents.mobile.form.description': 'Description',
    'agents.mobile.form.description.placeholder': 'One-line description of what this agent does',
    'agents.mobile.form.persona': 'Persona prompt',
    'agents.mobile.form.persona.placeholder': 'Define the agent\'s role, personality and boundaries',
    'agents.mobile.form.model': 'Model',
    'agents.mobile.form.model.placeholder': 'Choose a model',
    'agents.mobile.form.model.custom': 'Custom model',
    'agents.mobile.form.model.loadFailed': 'Failed to load models',
    'agents.mobile.form.temperature': 'Temperature',
    'agents.mobile.form.temperature.desc': 'Higher is more random, lower is more stable',
    'agents.mobile.form.memory': 'Long-term memory',
    'agents.mobile.form.memory.desc': 'Remember conversation context for continuous service',
    'agents.mobile.form.welcome': 'Welcome message',
    'agents.mobile.form.welcome.placeholder': 'Greeting the agent sends first',
    'agents.mobile.form.suggestedPrompts': 'Suggested prompts',
    'agents.mobile.form.suggestedPrompts.add': 'Add prompt',
    'agents.mobile.form.suggestedPrompts.placeholder': 'e.g. What can you do for me?',
    'agents.mobile.form.toast.created': 'Agent created',
    'agents.mobile.form.toast.updated': 'Changes saved',
    'agents.mobile.form.toast.published': 'Published',
    'agents.mobile.form.toast.createFailed': 'Failed to create, please retry',
    'agents.mobile.form.toast.updateFailed': 'Failed to save, please retry',
    'agents.mobile.form.toast.publishFailed': 'Failed to publish, please retry',
    'agents.mobile.form.toast.loadFailed': 'Agent not found or no access',
    'agents.mobile.form.toast.promptTooLong': 'Prompt cannot exceed 32768 characters',
    'agents.mobile.characters.title': 'My Characters',
    'agents.mobile.characters.create': 'New',
    'agents.mobile.characters.empty': 'No characters yet. Tap + to create one.',
    'agents.mobile.characters.menu.edit': 'Edit character',
    'agents.mobile.characters.menu.delete': 'Delete character',
    'agents.mobile.characters.confirm.delete.title': 'Delete character',
    'agents.mobile.characters.confirm.delete.desc': 'Delete "{{name}}"?',
    'agents.mobile.characters.confirm.cancel': 'Cancel',
    'agents.mobile.characters.confirm.ok': 'OK',
    'agents.mobile.characters.toast.deleted': 'Deleted',
    'agents.mobile.characters.form.title.create': 'New Character',
    'agents.mobile.characters.form.title.edit': 'Edit Character',
    'agents.mobile.characters.form.save': 'Save Character',
    'agents.mobile.characters.form.name': 'Name',
    'agents.mobile.characters.form.name.placeholder': 'e.g. Trip Planner',
    'agents.mobile.characters.form.name.required': 'Please enter a name',
    'agents.mobile.characters.form.voice': 'Voice',
    'agents.mobile.characters.form.voice.placeholder': 'Select a voice',
    'agents.mobile.characters.form.desc.label': 'Character setup / description',
    'agents.mobile.characters.form.desc.placeholder': 'Describe the character\'s personality, function or background...',
    'agents.mobile.characters.form.toast.created': 'Character created',
    'agents.mobile.characters.form.toast.updated': 'Character updated',
    'agents.mobile.characters.detail.title': 'Character Details',
    'agents.mobile.characters.detail.visibility.private': 'Private',
    'agents.mobile.characters.detail.systemPrompt': 'System prompt',
    'agents.mobile.characters.detail.systemPrompt.empty': 'No prompt set',
    'agents.mobile.characters.detail.voice': 'Voice',
    'agents.mobile.characters.detail.voice.default': 'Default voice',
    'agents.mobile.characters.detail.chat': 'Chat with TA',
    'agents.mobile.characters.detail.edit': 'Edit character',
    'agents.mobile.market.search': 'Search',
    'agents.mobile.market.search.placeholder': 'Search agents',
    'agents.mobile.market.search.cancel': 'Cancel',
    'agents.mobile.market.search.clear': 'Clear',
    'agents.mobile.market.search.empty': 'No matching agents found',
    'agents.mobile.market.create': 'Create agent',
    'agents.mobile.market.category.all': 'Featured',
    'agents.mobile.market.category.study': 'Study',
    'agents.mobile.market.category.work': 'Work',
    'agents.mobile.market.category.create': 'Creation',
    'agents.mobile.market.category.life': 'Life',
    'agents.mobile.market.category.fun': 'Fun',
    'agents.mobile.market.category.emotion': 'Emotion',
    'agents.mobile.market.category.game': 'Games',
    'agents.mobile.market.category.coding': 'Coding',
    'agents.mobile.market.category.drawing': 'Drawing',
    'agents.mobile.market.category.photo': 'Photo Q&A',
    'agents.mobile.market.category.device': 'Devices',
    'agents.mobile.market.hot.title': 'Hot searches',
    'agents.mobile.market.hot.coding': 'Code assistant',
    'agents.mobile.market.hot.writing': 'Xiaohongshu copy',
    'agents.mobile.market.hot.english': 'English speaking coach',
    'agents.mobile.market.hot.office': 'Resume optimization',
    'agents.mobile.market.hot.life': 'Trip planner',
    'agents.mobile.market.toast.loadFailed': 'Failed to load agents',
    'agents.mobile.market.error.title': 'Failed to load',
    'agents.mobile.market.error.desc': 'Network error or service unavailable, please retry later',
    'agents.mobile.market.error.retry': 'Retry',
    'agents.mobile.market.empty.title': 'No agents yet',
    'agents.mobile.market.empty.desc': 'Explore the agent ecosystem — create one to get started',
    'agents.mobile.market.empty.create': 'Create now',
  },
};

export function detectAgentH5Locale(): AgentH5Locale {
  const language =
    typeof navigator !== 'undefined' ? navigator.language : '';
  return language.toLowerCase().startsWith('en') ? 'en' : 'zh';
}

let activeAgentH5Locale: AgentH5Locale = detectAgentH5Locale();

/** Override the copy locale used by the mobile agent views (host hook). */
export function configureAgentH5Locale(locale: AgentH5Locale): void {
  activeAgentH5Locale = locale;
}

export function translateAgentMobileText(
  key: string,
  params?: Record<string, string>,
): string {
  const table = MOBILE_AGENT_COPY[activeAgentH5Locale] ?? MOBILE_AGENT_COPY.zh;
  const template = table[key] ?? key;
  if (!params) {
    return template;
  }
  return Object.entries(params).reduce(
    (value, [name, replacement]) => value.replaceAll(`{{${name}}}`, replacement),
    template,
  );
}

/** Convenience `t` helper bound to the active locale. */
export const t = translateAgentMobileText;
