name: sdkwork_agents_flutter_mobile_core
description: SDKWork Agents Flutter mobile core package
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sdkwork_agents_app_sdk:
    path: ../../../../sdks/sdkwork-agents-app-sdk/sdkwork-agents-app-sdk-flutter/generated/server-openapi

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sdkwork_common_flutter:
    path: ../../../../../sdkwork-sdk-commons/sdkwork-sdk-common-flutter
